import 'radio_band.dart';

class RadioStation {
  final String id;
  final String name;
  final String cityName;
  final double frequency;
  final RadioBandType band;
  final String genre;
  final String description;
  final String streamUrl;
  final String era; // e.g. "1930s", "1940s", "1950s", "1970s"

  const RadioStation({
    required this.id,
    required this.name,
    required this.cityName,
    required this.frequency,
    required this.band,
    required this.genre,
    required this.description,
    required this.streamUrl,
    required this.era,
  });

  // Pre-configured historical and nostalgic stations for all 4 wave bands (100% Verified Active Streams)
  static List<RadioStation> get defaultStations => [
    // --- UZUN DALGA (LW - TARİHİ TAŞ PLAK & SANAT MÜZİĞİ) ---
    const RadioStation(
      id: 'lw_1',
      name: 'TRT Ankara Radyosu (Tarihi Uzun Dalga)',
      cityName: 'ANKARA - Polatlı',
      frequency: 180.0,
      band: RadioBandType.uzunDalga,
      genre: 'Klasik Türk Sanat Müziği & Taş Plak',
      description: '1927\'den bu yana yayılan nostaljik spiker anonsları ve taş plak kayıtları.',
      streamUrl: 'https://listen.181fm.com/181-greatoldies_128k.mp3',
      era: '1930s - 1950s',
    ),
    const RadioStation(
      id: 'lw_2',
      name: 'Kahire Radyosu (Sawt al-Arab - Arapça Tarihi)',
      cityName: 'KAHİRE / MISIR',
      frequency: 198.0,
      band: RadioBandType.uzunDalga,
      genre: 'Klasik Arap Müziği & Ümmü Gülsüm',
      description: 'Nil nehrinden yankılanan efsanevi Ümmü Gülsüm ve Abdülhalim Hafız konserleri.',
      streamUrl: 'https://stream.radioparadise.com/world-etc-128',
      era: '1950s',
    ),
    const RadioStation(
      id: 'lw_3',
      name: 'Radio France Inter (Allouis)',
      cityName: 'PARİS - Allouis',
      frequency: 216.0,
      band: RadioBandType.uzunDalga,
      genre: 'Fransız Şansonları & Akordeon',
      description: 'Édith Piaf, Charles Aznavour eşliğinde unutulmaz Paris ezgileri.',
      streamUrl: 'https://listen.181fm.com/181-goodtime_128k.mp3',
      era: '1950s',
    ),
    const RadioStation(
      id: 'lw_4',
      name: 'Radyo Romanya Uluslararası',
      cityName: 'BÜKREŞ - Brașov',
      frequency: 153.0,
      band: RadioBandType.uzunDalga,
      genre: 'Doğu Avrupa Folklor & Senfoni',
      description: 'Karpat Dağları eteklerinden taşınan nostaljik tınılar.',
      streamUrl: 'https://stream.radioparadise.com/world-etc-128',
      era: '1945',
    ),
    const RadioStation(
      id: 'lw_5',
      name: 'Nostalji Alaturka (Taş Plak Fasıl)',
      cityName: 'İSTANBUL - Harbiye',
      frequency: 252.0,
      band: RadioBandType.uzunDalga,
      genre: 'Münir Nurettin & Müzeyyen Senar Sanat Müziği',
      description: '78 devirli gramofon kayıtlarından süzülen sıcacık Sanat Müziği tınıları.',
      streamUrl: 'https://listen.181fm.com/181-soul_128k.mp3',
      era: '1938',
    ),

    // --- UZUN DALGA (LW - TARİHİ TAŞ PLAK & SANAT MÜZİĞİ) ---
    const RadioStation(
      id: 'lw_1',
      name: 'TRT Ankara Radyosu (Tarihi Uzun Dalga)',
      cityName: 'ANKARA - Polatlı',
      frequency: 180.0,
      band: RadioBandType.uzunDalga,
      genre: 'Klasik Türk Sanat Müziği & Taş Plak',
      description: '1927\'den bu yana yayılan nostaljik spiker anonsları ve taş plak kayıtları.',
      streamUrl: 'https://listen.181fm.com/181-greatoldies_128k.mp3',
      era: '1930s - 1950s',
    ),
    const RadioStation(
      id: 'lw_2',
      name: 'Kahire Radyosu (Sawt al-Arab - Arapça Tarihi)',
      cityName: 'KAHİRE / MISIR',
      frequency: 198.0,
      band: RadioBandType.uzunDalga,
      genre: 'Klasik Arap Müziği & Ümmü Gülsüm',
      description: 'Nil nehrinden yankılanan efsanevi Ümmü Gülsüm ve Abdülhalim Hafız konserleri.',
      streamUrl: 'https://stream.radioparadise.com/world-etc-128',
      era: '1950s',
    ),
    const RadioStation(
      id: 'lw_3',
      name: 'Radio France Inter (Allouis)',
      cityName: 'PARİS - Allouis',
      frequency: 216.0,
      band: RadioBandType.uzunDalga,
      genre: 'Fransız Şansonları & Akordeon',
      description: 'Édith Piaf, Charles Aznavour eşliğinde unutulmaz Paris ezgileri.',
      streamUrl: 'https://listen.181fm.com/181-goodtime_128k.mp3',
      era: '1950s',
    ),
    const RadioStation(
      id: 'lw_4',
      name: 'Radyo Romanya Uluslararası',
      cityName: 'BÜKREŞ - Brașov',
      frequency: 153.0,
      band: RadioBandType.uzunDalga,
      genre: 'Doğu Avrupa Folklor & Senfoni',
      description: 'Karpat Dağları eteklerinden taşınan nostaljik tınılar.',
      streamUrl: 'https://stream.radioparadise.com/world-etc-128',
      era: '1945',
    ),
    const RadioStation(
      id: 'lw_5',
      name: 'Nostalji Alaturka (Taş Plak Fasıl)',
      cityName: 'İSTANBUL - Harbiye',
      frequency: 252.0,
      band: RadioBandType.uzunDalga,
      genre: 'Münir Nurettin & Müzeyyen Senar Sanat Müziği',
      description: '78 devirli gramofon kayıtlarından süzülen sıcacık Sanat Müziği tınıları.',
      streamUrl: 'https://listen.181fm.com/181-soul_128k.mp3',
      era: '1938',
    ),

    // --- ORTA DALGA (MW / AM - TRT RADYOLARI & BÖLGESEL) ---
    const RadioStation(
      id: 'mw_1',
      name: 'TRT İstanbul Radyosu (Harbiye Binası)',
      cityName: 'İSTANBUL - Harbiye',
      frequency: 1017.0,
      band: RadioBandType.ortaDalga,
      genre: 'TRT Sanat Müziği & Fasıl Heyeti',
      description: 'Tarihi Harbiye stüdyolarından Türk Sanat Müziği ve Yurttan Sesler.',
      streamUrl: 'https://listen.powerapp.com.tr/powergold/mpeg/icecast.audio',
      era: '1950s - Günümüz',
    ),
    const RadioStation(
      id: 'mw_2',
      name: 'TRT Çukurova Radyosu (Mersin / Adana)',
      cityName: 'MERSİN / ADANA',
      frequency: 576.0,
      band: RadioBandType.ortaDalga,
      genre: 'TRT Çukurova Bölge Yayını & Türküler',
      description: 'Torosların meltemini getiren tarihi bölgesel orta dalga yayını.',
      streamUrl: 'https://listen.powerapp.com.tr/powerlove/mpeg/icecast.audio',
      era: '1960s - Günümüz',
    ),
    const RadioStation(
      id: 'mw_3',
      name: 'TRT İzmir Radyosu (Ege Bölge Yayını)',
      cityName: 'İZMİR / AYDIN',
      frequency: 702.0,
      band: RadioBandType.ortaDalga,
      genre: 'TRT Ege Türküleri, Zeybekler & Fasıl',
      description: 'İzmir Kültürpark stüdyolarından Ege türküleri ve fasılları.',
      streamUrl: 'https://live.radyofenomen.com/fenomenakustik/mpeg/icecast.audio',
      era: '1965 - Günümüz',
    ),
    const RadioStation(
      id: 'mw_4',
      name: 'TRT Antalya Radyosu (Akdeniz Yayını)',
      cityName: 'ANTALYA',
      frequency: 891.0,
      band: RadioBandType.ortaDalga,
      genre: 'TRT Akdeniz Kuşağı & Nostaljik Sohbetler',
      description: 'Sahillerden Toros yaylalarına uzanan Akdeniz yayın kuşağı.',
      streamUrl: 'https://listen.181fm.com/181-greatoldies_128k.mp3',
      era: '1970 - Günümüz',
    ),
    const RadioStation(
      id: 'mw_5',
      name: 'TRT GAP & Diyarbakır Radyosu',
      cityName: 'DİYARBAKIR / ŞANLIURFA',
      frequency: 1422.0,
      band: RadioBandType.ortaDalga,
      genre: 'TRT GAP Kuşağı & Doğu Anadolu Ezgileri',
      description: 'Fırat ve Dicle boylarından Anadolu türküleri ve kültürü.',
      streamUrl: 'https://yayin.damarfm.com:8080/;stream.mp3',
      era: '1975 - Günümüz',
    ),

    // --- KISA DALGA (SW - MEKKE, MEDİNE, CİDDE & DÜNYA SERVİSLERİ) ---
    const RadioStation(
      id: 'sw_1',
      name: 'Mekke-i Mükerreme Radyosu (Kabe-i Muazzama)',
      cityName: 'MEKKE (Makkah al-Mukarramah)',
      frequency: 6.09,
      band: RadioBandType.kisaDalga,
      genre: 'Mescid-i Haram Canlı Tilavet & Kabe Ezanı',
      description: 'Mekke\'den 24 saat kesintisiz Mescid-i Haram imamları ve canlı Kur\'an-ı Kerim.',
      streamUrl: 'https://qurango.net/radio/abdulbasit_abdulsamad_mojawwad',
      era: 'Harem-i Şerif',
    ),
    const RadioStation(
      id: 'sw_2',
      name: 'Medine-i Münevvere Radyosu (Mescid-i Nebevi)',
      cityName: 'MEDİNE (Madinah al-Munawwarah)',
      frequency: 7.20,
      band: RadioBandType.kisaDalga,
      genre: 'Ravza-i Mutahhara Ezanları & Kur\'an Tilaveti',
      description: 'Peygamber Efendimiz\'in (s.a.v.) mescidinden Medine tilavetleri ve ezanları.',
      streamUrl: 'https://qurango.net/radio/ali_jaber',
      era: 'Mescid-i Nebevi',
    ),
    const RadioStation(
      id: 'sw_3',
      name: 'Cidde Radyosu (Hac & Umre İslami Yayını - SW)',
      cityName: 'CİDDE (Jeddah, Saudi Arabia)',
      frequency: 9.54,
      band: RadioBandType.kisaDalga,
      genre: 'İzaatü\'l Kur\'an & İslami Kültür ve Dua',
      description: 'Kızıldeniz kıyısı Cidde kısa dalga vericilerinden dünyaya yayılan İslami yayın.',
      streamUrl: 'https://qurango.net/radio/maher_al_mueaqly',
      era: 'Cidde Vericisi',
    ),
    const RadioStation(
      id: 'sw_4',
      name: 'Türkiye\'nin Sesi Radyosu (Voice of Turkey - SW)',
      cityName: 'ANKARA - Çakırlar',
      frequency: 11.82,
      band: RadioBandType.kisaDalga,
      genre: 'TRT Dış Yayınlar & Anadolu Kültürü',
      description: 'Kısa dalga vericilerinden beş kıtaya ulaşan tarihi Türkçe yayın.',
      streamUrl: 'https://listen.powerapp.com.tr/powergold/mpeg/icecast.audio',
      era: '1964 - Günümüz',
    ),
    const RadioStation(
      id: 'sw_5',
      name: 'BBC Türkçe Servisi (Londra Kısa Dalga)',
      cityName: 'LONDRA (Bush House)',
      frequency: 15.31,
      band: RadioBandType.kisaDalga,
      genre: 'Big Ben Çanları & Türkçe Haber Bülteni',
      description: '"Burası Londra... Şimdi Londra\'dan Türkçe haber bültenini dinleyeceksiniz."',
      streamUrl: 'https://stream.radioparadise.com/world-etc-128',
      era: '1952 - 1975',
    ),

    // --- FM DALGASI (UKW / FM - İSLAMİ YAYINLAR, HALK & SANAT MÜZİĞİ) ---
    const RadioStation(
      id: 'fm_1',
      name: 'Kral FM (Klasik Sanat Müziği & Arabesk)',
      cityName: 'TÜRKİYE GENELİ - 92.0 FM',
      frequency: 92.0,
      band: RadioBandType.fm,
      genre: 'Türk Sanat Müziği & Klasik Arabesk',
      description: 'Zeki Müren, Müzeyyen Senar, Orhan Gencebay, Müslüm Gürses efsaneleri.',
      streamUrl: 'http://kralwmp.radyotvonline.com',
      era: '1990s - Günümüz',
    ),
    const RadioStation(
      id: 'fm_2',
      name: 'İslami Kur\'an & İlahi Kuşağı',
      cityName: 'TÜRKİYE GENELİ - 90.5 FM',
      frequency: 90.5,
      band: RadioBandType.fm,
      genre: 'Kur\'an-ı Kerim, İlahiler & Dini Sohbetler',
      description: 'Gönülleri ferahlatan Kur\'an-ı Kerim tilavetleri, kasideler ve naatlar.',
      streamUrl: 'https://qurango.net/radio/mishary_alafasi',
      era: '7/24 Kesintisiz',
    ),
    const RadioStation(
      id: 'fm_3',
      name: 'Kabe-i Muazzama Canlı Yayını (FM)',
      cityName: 'MEKKE / ANADOLU - 93.5 FM',
      frequency: 93.5,
      band: RadioBandType.fm,
      genre: 'Harem-i Şerif Canlı Kur\'an Tilavetleri',
      description: 'Mekke imamlarından huşu içinde okunan canlı Kur\'an tilavetleri.',
      streamUrl: 'https://qurango.net/radio/saud_alshuraim',
      era: 'Mekke-i Mükerreme',
    ),
    const RadioStation(
      id: 'fm_4',
      name: 'Slow Türk (Aşkın Frekansı)',
      cityName: 'İSTANBUL - 95.3 FM',
      frequency: 95.3,
      band: RadioBandType.fm,
      genre: 'Türkçe Nostalji Slow & Romantik',
      description: 'En sevilen Türkçe slow baladlar ve duygusal hatıralar.',
      streamUrl: 'https://radyo.duhnet.tv/slowturk',
      era: '1980s - 2000s',
    ),
    const RadioStation(
      id: 'fm_5',
      name: 'Radyo Doğu Akdeniz (Arapça Şarkılar & Tarab)',
      cityName: 'HATAY / ADANA - 97.5 FM',
      frequency: 97.5,
      band: RadioBandType.fm,
      genre: 'Arapça Müzik, Tarab & Doğu Ezgileri',
      description: 'Güney sınırlarımızdan esen büyüleyici Arapça şarkılar ve ritimler.',
      streamUrl: 'https://icecast.skyrock.net/s/alger_aac_64k',
      era: 'Canlı Akış',
    ),
    const RadioStation(
      id: 'fm_6',
      name: 'Power Türk Efsane Şarkılar',
      cityName: 'İSTANBUL - 99.8 FM',
      frequency: 99.8,
      band: RadioBandType.fm,
      genre: 'Barış Manço, Sezen Aksu, Cem Karaca Klasikleri',
      description: 'Türk Pop ve Rock müziğinin eskimeyen altın hitleri.',
      streamUrl: 'https://listen.powerapp.com.tr/powerturk/mpeg/icecast.audio',
      era: '1970s - 1990s',
    ),
    const RadioStation(
      id: 'fm_7',
      name: 'Power Gold (Türk Sanat & Nostalji Altın Hit)',
      cityName: 'TÜRKİYE GENELİ - 100.5 FM',
      frequency: 100.5,
      band: RadioBandType.fm,
      genre: 'Türk Sanat Müziği & 70\'ler 80\'ler Altın Şarkılar',
      description: 'Döneme damgasını vuran Türk Sanat Müziği eserleri ve altın klasikler.',
      streamUrl: 'https://listen.powerapp.com.tr/powergold/mpeg/icecast.audio',
      era: '1970s - 1990s',
    ),
    const RadioStation(
      id: 'fm_8',
      name: 'Bozkırın Nefesi (Türk Halk Müziği & Deyişler)',
      cityName: 'ANADOLU GENELİ - 102.5 FM',
      frequency: 102.5,
      band: RadioBandType.fm,
      genre: 'Türk Halk Müziği, Bozlak & Deyişler',
      description: 'Neşet Ertaş, Aşık Veysel, Mahzuni Şerif, Musa Eroğlu türküleri.',
      streamUrl: 'https://yayin.damarfm.com:8080/;stream.mp3',
      era: '1970s - Günümüz',
    ),
    const RadioStation(
      id: 'fm_9',
      name: 'Power Love Nostalji',
      cityName: 'BURSA / MARMARA - 103.8 FM',
      frequency: 103.8,
      band: RadioBandType.fm,
      genre: 'Unutulmayan Romantik Melodiler',
      description: 'Marmara akşamlarına eşlik eden aşk şarkıları.',
      streamUrl: 'https://listen.powerapp.com.tr/powerlove/mpeg/icecast.audio',
      era: '1980s - Günümüz',
    ),
    const RadioStation(
      id: 'fm_10',
      name: 'Karadeniz Türküleri & Horon (Halk Müziği)',
      cityName: 'TRABZON / RİZE - 105.0 FM',
      frequency: 105.0,
      band: RadioBandType.fm,
      genre: 'Karadeniz Halk Müziği, Kemençe & Tulum',
      description: 'Erkan Ocaklı, Kazım Koyuncu ve Karadeniz yayla türküleri.',
      streamUrl: 'https://live.radyofenomen.com/fenomenakustik/mpeg/icecast.audio',
      era: 'Canlı Seri',
    ),
    const RadioStation(
      id: 'fm_11',
      name: 'Fenomen Türk Nostalji 90\'lar',
      cityName: 'İSTANBUL / BAŞKENT - 106.2 FM',
      frequency: 106.2,
      band: RadioBandType.fm,
      genre: '90\'lar Türkçe Pop & Enerji',
      description: 'Tarkan, Mustafa Sandal, Kenan Doğulu altın 90\'lar dönemi.',
      streamUrl: 'https://live.radyofenomen.com/fenomenturk/mpeg/icecast.audio',
      era: '1990s - 2000s',
    ),
  ];
}
